# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
namespace: api
image:
  name: iampaavan/csye-7374-advanced-cloud-webapp-backend:62747894aa788611a7b160868c92489472226c1d
  pullPolicy: IfNotPresent
imagePullSecrets: dockercreds
#nameOverride: ""
#fullnameOverride: ""

service:
  name: api-backend
  type: LoadBalancer
  port: 80
dbsecret:
  name: django-backend-secret
  #PROD RDS URL
  #  rdsurl: postgres-rds-instance.cn7jkyipepdl.us-east-1.rds.amazonaws.com
  # DEV RDS URL
  rdsurl: ""
imageCredentials:
  registry: https://index.docker.io/v1/
  username:
  password:
bucketname: ""
awsAccessKey: ""
awsSecretKey: ""
#PROD CONFIG
#bucketname:
#awsAccessKey:
#awsSecretKey:
redis:
  password:
redisport: 6379
initContainers:
  name: busybox:1.28
ingress:
  host: dev.paavangopala.me
